//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sander.DirLister.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class History : global::System.Configuration.ApplicationSettingsBase {
        
        private static History defaultInstance = ((History)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new History())));
        
        public static History Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DirectoryHistory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DirectoryHistory"]));
            }
            set {
                this["DirectoryHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection WildcardFilter {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["WildcardFilter"]));
            }
            set {
                this["WildcardFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegexFilter {
            get {
                return ((string)(this["RegexFilter"]));
            }
            set {
                this["RegexFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int DirectoryHistoryLength {
            get {
                return ((int)(this["DirectoryHistoryLength"]));
            }
            set {
                this["DirectoryHistoryLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int FilterHistoryLength {
            get {
                return ((int)(this["FilterHistoryLength"]));
            }
            set {
                this["FilterHistoryLength"] = value;
            }
        }
    }
}
